import { VpnNode, SubscriptionPlan, LinkedDevice, ThreatNotification, SecuritySettings } from '../types';

export const MOCK_NODES: VpnNode[] = [
  {
    id: 'node-mesh-prime',
    name: 'CONTINENT Core - Neural Mesh',
    codename: 'NEXUS-01-AUTO',
    region: 'Auto-Routing Intelligent',
    countryCode: 'AF',
    flagEmoji: '🌐',
    ping: 12,
    load: 28,
    isRecommended: true,
    tier: 'free',
    ipAddress: '102.164.218.42',
  },
  {
    id: 'node-lagos-cyber',
    name: 'Lagos Cyber Gateway',
    codename: 'LOS-SHIELD-04',
    region: 'Afrique de l’Ouest',
    countryCode: 'NG',
    flagEmoji: '🇳🇬',
    ping: 18,
    load: 34,
    tier: 'free',
    ipAddress: '197.210.64.11',
  },
  {
    id: 'node-frankfurt-ghost',
    name: 'Frankfurt Quantum Vault',
    codename: 'FRA-GHOST-09',
    region: 'Europe Centrale',
    countryCode: 'DE',
    flagEmoji: '🇩🇪',
    ping: 24,
    load: 42,
    isPremium: true,
    tier: 'premium',
    ipAddress: '185.122.56.90',
  },
  {
    id: 'node-tokyo-matrix',
    name: 'Tokyo Cyber Matrix',
    codename: 'TYO-NEON-07',
    region: 'Asie Pacifique',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    ping: 46,
    load: 58,
    isPremium: true,
    tier: 'premium',
    ipAddress: '133.242.18.204',
  },
  {
    id: 'node-zurich-vault',
    name: 'Zurich Swiss Bunker',
    codename: 'ZRH-STEALTH-01',
    region: 'Europe / No-Logs Vault',
    countryCode: 'CH',
    flagEmoji: '🇨🇭',
    ping: 29,
    load: 19,
    isPremium: true,
    tier: 'ultimate',
    ipAddress: '178.209.51.88',
  },
  {
    id: 'node-singapore-quantum',
    name: 'Singapore Deep Harbor',
    codename: 'SIN-HYPER-03',
    region: 'Asie du Sud-Est',
    countryCode: 'SG',
    flagEmoji: '🇸🇬',
    ping: 52,
    load: 35,
    isPremium: true,
    tier: 'premium',
    ipAddress: '119.81.72.14',
  },
  {
    id: 'node-johannesburg-speed',
    name: 'Johannesburg Apex Hub',
    codename: 'JNB-SPEED-02',
    region: 'Afrique Australe',
    countryCode: 'ZA',
    flagEmoji: '🇿🇦',
    ping: 21,
    load: 40,
    tier: 'free',
    ipAddress: '196.25.1.1',
  },
];

export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: 'basic',
    title: 'Basique Cyber',
    monthlyPrice: 5.99,
    quarterlyPrice: 14.99,
    annualPrice: 49.99,
    features: [
      'Accès au réseau CONTINENT Standard',
      'Protection Kill Switch active',
      '2 appareils simultanés',
      'Politique stricte sans journaux (Zero-Log)',
      'Débit garanti 300 Mb/s',
    ],
    maxDevices: 2,
    speedLimit: '300 Mb/s',
    supportLevel: 'Email standard 24/7',
  },
  {
    id: 'premium',
    title: 'Premium Guardian',
    badge: 'POPULAIRE',
    isPopular: true,
    monthlyPrice: 9.99,
    quarterlyPrice: 24.99,
    annualPrice: 79.99,
    features: [
      'Réseau neuronal CONTINENT Core illimité',
      'Protocole WireGuard-X ultra-véloce',
      'Bouclier Cybernétique (anti-malware & pubs)',
      '5 appareils simultanés',
      'Débit illimité (jusqu’à 10 Gb/s)',
      'Aura Guardian animé en temps réel',
      'Support prioritaire en direct',
    ],
    maxDevices: 5,
    speedLimit: 'Ultra 10 Gb/s',
    supportLevel: 'Guardian Chat Prioritaire',
  },
  {
    id: 'ultimate',
    title: 'Ultime Quantum',
    badge: 'MAXIMUM',
    monthlyPrice: 14.99,
    quarterlyPrice: 38.99,
    annualPrice: 119.99,
    features: [
      'Toutes les fonctionnalités Premium incluses',
      'Appareils connectés illimités',
      'Double-Hop & Brouillage quantique stealth',
      'Adresse IP dédiée sur demande',
      'Protection contre les fuites DNS et WebRTC',
      'Canal VIP gaming et streaming 4K HDR',
      'Assistance ingénieur dédiée 24/7/365',
    ],
    maxDevices: 99,
    speedLimit: 'Bande passante non bridée',
    supportLevel: 'Ingénieur Sécurité Dédié',
  },
];

export const MOCK_DEVICES: LinkedDevice[] = [
  {
    id: 'dev-01',
    name: 'iPhone 15 Pro Max',
    deviceType: 'ios',
    ipAddress: '10.8.0.2 (Protégé)',
    lastActive: 'Actif en ce moment',
    isCurrentDevice: true,
    osVersion: 'iOS 18.2',
  },
  {
    id: 'dev-02',
    name: 'MacBook Pro M3 Max',
    deviceType: 'macos',
    ipAddress: '10.8.0.5',
    lastActive: 'Il y a 14 minutes',
    isCurrentDevice: false,
    osVersion: 'macOS Sequoia 15.1',
  },
  {
    id: 'dev-03',
    name: 'Station de Travail Linux',
    deviceType: 'linux',
    ipAddress: '10.8.0.8',
    lastActive: 'Il y a 3 heures',
    isCurrentDevice: false,
    osVersion: 'Ubuntu 24.04 LTS',
  },
];

export const MOCK_NOTIFICATIONS: ThreatNotification[] = [
  {
    id: 'notif-01',
    title: 'Bouclier Cyber Actif',
    message: '14 traqueurs publicitaires et 2 scripts malveillants neutralisés avec succès.',
    timestamp: 'Il y a 5 min',
    category: 'threat',
    severity: 'medium',
    read: false,
  },
  {
    id: 'notif-02',
    title: 'Connexion Sécurisée Établie',
    message: 'Tunnel chiffré AES-256 activé via CONTINENT Core - Neural Mesh.',
    timestamp: 'Il y a 25 min',
    category: 'connection',
    severity: 'low',
    read: false,
  },
  {
    id: 'notif-03',
    title: 'Nouveau Nœud Haute Vitesse',
    message: 'Le nœud Francfort Quantum Vault a été optimisé avec 40% de latence en moins.',
    timestamp: 'Hier',
    category: 'system',
    severity: 'low',
    read: true,
  },
  {
    id: 'notif-04',
    title: 'Abonnement Premium Actif',
    message: 'Votre compte bénéficie de la protection Guardian maximale jusqu’au 30 Septembre 2027.',
    timestamp: 'Il y a 3 jours',
    category: 'account',
    severity: 'low',
    read: true,
  },
];

export const DEFAULT_SETTINGS: SecuritySettings = {
  killSwitch: true,
  splitTunneling: false,
  cyberShield: true,
  dnsLeakProtection: true,
  autoConnectOnUntrustedWifi: true,
  quantumObfuscation: true,
  biometricLock: false,
  selectedProtocol: 'CONTINENT-CORE',
  routingMode: 'intelligent',
  notificationsEnabled: true,
};
